### ISSUE TITLE
Management API v0.1.117 breaks Cassandra 5.0.2 UBI metrics endpoint with Netty NoSuchMethodError

### ISSUE THREAD

**Issue by prathpatkar-fynd** [k8ssandra/management-api-for-apache-cassandra#755]
With K8ssandra Cassandra 5.0.2:

```text
cr.k8ssandra.io/k8ssandra/cass-management-api:5.0.2-ubi
```

After pods pulled an image containing Management API `v0.1.117`, the Cassandra metrics endpoint on port `9000` started resetting connections.

## Failing Pod Contents

```text
/opt/management-api/datastax-mgmtapi-agent-5.0.x-0.1.117.jar
/opt/management-api/datastax-mgmtapi-server-0.1.117.jar
/opt/cassandra/lib/netty-codec-4.1.96.Final.jar
/opt/cassandra/lib/netty-handler-4.1.96.Final.jar
```

## Reproduction

From inside the Cassandra container:

```bash
curl -v http://127.0.0.1:9000/metrics
```

Result:

```text
Connected to 127.0.0.1:9000
Recv failure: Connection reset by peer
curl: (56) Recv failure: Connection reset by peer
```

## Logs

```text
java.lang.NoSuchMethodError:
'io.netty.handler.codec.compression.SnappyOptions io.netty.handler.codec.compression.StandardCompressionOptions.snappy()'
    at io.netty.handler.codec.http.HttpContentCompressor.defaultCompressionOptions(HttpContentCompressor.java:241)
    at io.netty.handler.codec.http.HttpContentCompressor.<init>(HttpContentCompressor.java:183)
    at io.netty.handler.codec.http.HttpContentCompressor.<init>(HttpContentCompressor.java:71)
    at io.k8ssandra.metrics.http.NettyHttpInitializer.initChannel(NettyHttpInitializer.java:30)
```

## Expected Behavior

`GET /metrics` on port `9000` returns HTTP `200` with Prometheus metrics.

## Observed Behavior

The TCP connection is accepted, then reset. Prometheus scrape fails with:

```text
connection reset by peer
```

## Comparison

Pods using older Management API versions work with the same Cassandra `5.0.2` setup.

Working version:

```text
/opt/management-api/datastax-mgmtapi-agent-5.0.x-0.1.113.jar
/opt/management-api/datastax-mgmtapi-server-0.1.113.jar
```

```bash
curl http://127.0.0.1:9000/metrics
```

Returns:

```text
200
```

Failing version:

```text
/opt/management-api/datastax-mgmtapi-agent-5.0.x-0.1.117.jar
/opt/management-api/datastax-mgmtapi-server-0.1.117.jar
```

```bash
curl http://127.0.0.1:9000/metrics
```

Returns:

```text
connection reset by peer
```

## Likely Cause

`v0.1.117` appears to call:

```text
io.netty.handler.codec.compression.StandardCompressionOptions.snappy()
```

but the Cassandra `5.0.2` image contains Netty `4.1.96.Final` jars where that method/signature is not available.

This looks like a Netty dependency/classpath mismatch in the metrics HTTP path.

## Impact

Cassandra remains `Ready`, but Prometheus cannot scrape Cassandra metrics from affected pods. This causes monitoring gaps while the database process itself appears healthy.

## Questions

1. Is Management API `v0.1.117` expected to be compatible with Cassandra `5.0.2` UBI images?
2. Should the metrics HTTP server avoid `HttpContentCompressor`, or should Netty dependencies be aligned/shaded?
3. Is there a recommended fixed Management API version/tag for Cassandra `5.0.2-ubi`?

**Comment by emerkle826** [comment]
Thanks for reporting this. The problem here is that as Cassandra versions progress, the dependencies that Cassandra "provides" that Management API Agents rely on may change. At some point Cassandra 5.0 upgraded to Netty 4.1.130.Final, and apparently the internals of Netty between 4.1.96.Final and 4.1.130.Final aren't compatible in this context.

What complicates things is that Cassandra 5.0 explicitly excludes `netty-codec-http` from its `netty-all`dependency, and the Metrics endpoint that Management API provides explicitly needs `netty-codec-http`. So the Agent for Cassandra 5.0 has to include `netty-codec-http`, but it needs to include the same version as the rest of the Netty libraries that Cassandra provides. There are tests for the Metrics endpoint, but unfortunately they only run against the latest version of each of the DB Server versions, so once the Agent updated its `netty-codec-http` version, it broke the Metrics endpoint for any versions of Cassandra 5.0.x that don't have the matching Netty version.

I have a work-in-progress branch I've been tinkering with locally to try to address this, but it's nowhere near ready to be merged. In the meantime, a workaround is to use an image with a newer Cassandra (5.0.8 works), unless you specifically have to stay on 5.0.2. I may be able to get something up soon to address it for all versions.

**Comment by emerkle826** [comment]
@prathpatkar-fynd Again, thanks for the issue report. I have addressed this in the release that went out yesterday (v0.1.118).

**Comment by prathpatkar-fynd** [comment]
Thanks @emerkle826 for the quick fix and explanation. Missing `netty-codec-http` from Cassandra 5.0 makes sense.

I have tested `v0.1.118` with `Cassandra 5.0.2 UBI` setup and confirmed the metrics endpoint is working again, thanks 👍
