### PR TITLE
Fix Metrics endpoint for older Cassandra 5.0.X

### LINKED ISSUE #755: Management API v0.1.117 breaks Cassandra 5.0.2 UBI metrics endpoint with Netty NoSuchMethodError
With K8ssandra Cassandra 5.0.2:

```text
cr.k8ssandra.io/k8ssandra/cass-management-api:5.0.2-ubi
```

After pods pulled an image containing Management API `v0.1.117`, the Cassandra metrics endpoint on port `9000` started resetting connections.

## Failing Pod Contents

```text
/opt/management-api/datastax-mgmtapi-agent-5.0.x-0.1.117.jar
/opt/management-api/datastax-mgmtapi-server-0.1.117.jar
/opt/cassandra/lib/netty-codec-4.1.96.Final.jar
/opt/cassandra/lib/netty-handler-4.1.96.Final.jar
```

## Reproduction

From inside the Cassandra container:

```bash
curl -v http://127.0.0.1:9000/metrics
```

Result:

```text
Connected to 127.0.0.1:9000
Recv failure: Connection reset by peer
curl: (56) Recv failure: Connection reset by peer
```

## Logs

```text
java.lang.NoSuchMethodError:
'io.netty.handler.codec.compression.SnappyOptions io.netty.handler.codec.compression.StandardCompressionOptions.snappy()'
    at io.netty.handler.codec.http.HttpContentCompressor.defaultCompressionOptions(HttpContentCompressor.java:241)
    at io.netty.handler.codec.http.HttpContentCompressor.<init>(HttpContentCompressor.java:183)
    at io.netty.handler.codec.http.HttpContentCompressor.<init>(HttpContentCompressor.java:71)
    at io.k8ssandra.metrics.http.NettyHttpInitializer.initChannel(NettyHttpInitializer.java:30)
```

## Expected Behavior

`GET /metrics` on port `9000` returns HTTP `200` with Prometheus metrics.

## Observed Behavior

The TCP connection is accepted, then reset. Prometheus scrape fails with:

```text
connection reset by peer
```

## Comparison

Pods using older Management API versions work with the same Cassandra `5.0.2` setup.

Working version:

```text
/opt/management-api/datastax-mgmtapi-agent-5.0.x-0.1.113.jar
/opt/management-api/datastax-mgmtapi-server-0.1.113.jar
```

```bash
curl http://127.0.0.1:9000/metrics
```

Returns:

```text
200
```

Failing version:

```text
/opt/management-api/datastax-mgmtapi-agent-5.0.x-0.1.117.jar
/opt/management-api/datastax-mgmtapi-server-0.1.117.jar
```

```bash
curl http://127.0.0.1:9000/metrics
```

Returns:

```text
connection reset by peer
```

## Likely Cause

`v0.1.117` appears to call:

```text
io.netty.handler.codec.compression.StandardCompressionOptions.snappy()
```

but the Cassandra `5.0.2` image contains Netty `4.1.96.Final` jars where that method/signature is not available.

This looks like a Netty dependency/classpath mismatch in the metrics HTTP path.

## Impact

Cassandra remains `Ready`, but Prometheus cannot scrape Cassandra metrics from affected pods. This causes monitoring gaps while the database process itself appears healthy.

## Questions

1. Is Management API `v0.1.117` expected to be compatible with Cassandra `5.0.2` UBI images?
2. Should the metrics HTTP server avoid `HttpContentCompressor`, or should Netty dependencies be aligned/shaded?
3. Is there a recommended fixed Management API version/tag for Cassandra `5.0.2-ubi`?

### PR DESCRIPTION
**Pull request by emerkle826**
This patch explicitly adds `netty-codec-http` as a "provided" dependency to the agent-common module and adds the library to the Docker images built for Cassandra 5.0 and newer.

The need for this is due to Cassandra 5.0 and newer excluding `netty-codec-http` from its `netty-all` dependency, but the internal Metrics implementation relies on this library. This patch also figures out which version of the library is needed in the Dockerfile updates so that we match `netty-codec-http` version with the rest of the Netty libraries that come with Cassandra. This change in the Dockerfile is due to the fact that different versions of Cassandra 5.0 include different versions of Netty, and we can't use a static `netty-codec-http` library across them all.

Fixes #755

### CODE REVIEW

**Comment by emerkle826** [comment]
I added a Cassandra 5.0.2 specific Metrics test and it passes: https://github.com/k8ssandra/management-api-for-apache-cassandra/actions/runs/26188313276/job/77050722727
